CREATE TABLE vote(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    distro VARCHAR(15) NOT NULL,
    username VARCHAR(30) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT current_timestamp() 
);

CREATE TABLE user(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(100) NOT NULL,
    passwd VARCHAR(500) NOT NULL
)